apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credential-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /api/issue
            pathType: Prefix
            backend:
              service:
                name: issue-service
                port:
                  number: 80
          - path: /api/verify
            pathType: Prefix
            backend:
              service:
                name: verify-service
                port:
                  number: 80
